//! Pins `engine::build_args` and `engine::classify_exit` to a fixed set of
//! configurations, so a behaviour change shows up as a reviewed diff to
//! `scenarios()` below instead of a silent regression. Every fixture here is
//! plain, typed Rust: there is no external harness and nothing is read from
//! disk at test time.

use std::path::Path;

use mimirdlp::engine::{
    Archive, AudioExtraction, AudioFormat, ContainerConversion, Options, Outcome, Playlist,
    SponsorBlock, Subtitles, ThumbnailFormat, build_args, classify_exit,
};

struct Scenario {
    name: &'static str,
    options: Options,
    output_dir: Option<&'static str>,
    urls: &'static [&'static str],
    /// The argv `build_args` must produce. Tool paths are written the Linux
    /// way (`<SCRIPT_DIR>/bin/ffmpeg`, no extension, `/`); `normalize_tool_path`
    /// makes that comparable to what Windows actually produces.
    argv: &'static [&'static str],
    /// The exit code the downloader reports to the user.
    exit: i32,
    /// The exit code yt-dlp itself would have returned. Differs from `exit`
    /// only for 101, which is success from the user's point of view.
    fake_exit: i32,
}

fn scenarios() -> Vec<Scenario> {
    vec![
        Scenario {
            name: "advanced_all",
            options: Options {
                verbose: false,
                restrict_filenames: false,
                preserve_mtime: true,
                ignore_errors: true,
                concurrent_fragments: 8,
                sleep_requests: 2.5,
                limit_rate: Some("500K".into()),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "2.5",
                "--concurrent-fragments",
                "8",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "--limit-rate",
                "500K",
                "-f",
                "bestvideo*+bestaudio/best",
                "-i",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--mtime",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "archive_and_limit",
            options: Options {
                archive: Some(Archive {
                    file: "download_archive.txt".into(),
                    break_on_existing: false,
                }),
                max_downloads: Some(7),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--download-archive",
                "download_archive.txt",
                "--max-downloads",
                "7",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "archive_break_file",
            options: Options {
                archive: Some(Archive {
                    file: "hist.txt".into(),
                    break_on_existing: true,
                }),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--download-archive",
                "hist.txt",
                "--break-on-existing",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "audio_flac",
            options: Options {
                format: "bestaudio/best".into(),
                extract_audio: Some(AudioExtraction {
                    format: AudioFormat::Flac,
                    quality: Some(0),
                }),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--merge-output-format",
                "mkv",
                "--extract-audio",
                "--audio-format",
                "flac",
                "--audio-quality",
                "0",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "audio_mp3_q2",
            options: Options {
                format: "bestaudio/best".into(),
                extract_audio: Some(AudioExtraction {
                    format: AudioFormat::Mp3,
                    quality: Some(2),
                }),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--merge-output-format",
                "mkv",
                "--extract-audio",
                "--audio-format",
                "mp3",
                "--audio-quality",
                "2",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "audio_then_video_only",
            options: Options {
                format: "bestvideo".into(),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "audio_wav",
            options: Options {
                format: "bestaudio/best".into(),
                extract_audio: Some(AudioExtraction {
                    format: AudioFormat::Wav,
                    quality: Some(0),
                }),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestaudio/best",
                "--merge-output-format",
                "mkv",
                "--extract-audio",
                "--audio-format",
                "wav",
                "--audio-quality",
                "0",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "exit_101_is_success",
            options: Options {
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 101,
        },
        Scenario {
            name: "exit_1_download_error",
            options: Options {
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 1,
            fake_exit: 1,
        },
        Scenario {
            name: "exit_1_sponsorblock",
            options: Options {
                sponsorblock: SponsorBlock::Mark {
                    categories: "sponsor".into(),
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--sponsorblock-mark",
                "sponsor",
                "--embed-chapters",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 1,
            fake_exit: 1,
        },
        Scenario {
            name: "exit_2_argument_error",
            options: Options {
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 2,
            fake_exit: 2,
        },
        Scenario {
            name: "format_audio_only",
            options: Options {
                format: "bestaudio".into(),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestaudio",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>opus",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "format_custom",
            options: Options {
                format: "bv*[height<=720]+ba/b".into(),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bv*[height<=720]+ba/b",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "format_max_res",
            options: Options {
                max_resolution: Some(1080),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--format-sort",
                "res:1080",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "format_premerged",
            options: Options {
                format: "best".into(),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "format_video_only",
            options: Options {
                format: "bestvideo".into(),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "limit_without_archive",
            options: Options {
                max_downloads: Some(3),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--max-downloads",
                "3",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "live_menu",
            options: Options {
                live_from_start: true,
                wait_for_video: Some("60-3600".into()),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--live-from-start",
                "--wait-for-video",
                "60-3600",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "menu_default",
            options: Options {
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "meta_all",
            options: Options {
                embed_metadata: true,
                embed_chapters: true,
                embed_info_json: true,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--embed-metadata",
                "--embed-chapters",
                "--embed-info-json",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "meta_basic",
            options: Options {
                embed_metadata: true,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--embed-metadata",
                "--no-embed-chapters",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "meta_chapters",
            options: Options {
                embed_metadata: true,
                embed_chapters: true,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--embed-metadata",
                "--embed-chapters",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "no_playlist",
            options: Options {
                playlist: Playlist::Single,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--no-playlist",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "outdir_tilde_create",
            options: Options {
                ..Options::default()
            },
            output_dir: Some("<HOME>/Videos/yt"),
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-P",
                "<HOME>/Videos/yt",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "playlist_folders",
            options: Options {
                organize_playlist_folders: true,
                playlist: Playlist::Whole {
                    items: None,
                    reverse: false,
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--yes-playlist",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(playlist)s/%(playlist_index)02d - %(title)s.%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "playlist_items",
            options: Options {
                playlist: Playlist::Whole {
                    items: Some("1-5".into()),
                    reverse: false,
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--yes-playlist",
                "-I",
                "1-5",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "playlist_reverse",
            options: Options {
                playlist: Playlist::Whole {
                    items: None,
                    reverse: true,
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--yes-playlist",
                "--playlist-reverse",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "quick_dashdash_id",
            options: Options {
                ..Options::default()
            },
            output_dir: None,
            urls: &["-xxxxxxxxxx"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "-xxxxxxxxxx",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "quick_default",
            options: Options {
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "quick_live",
            options: Options {
                live_from_start: true,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--live-from-start",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "quick_multiple_urls",
            options: Options {
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/a", "https://example.com/b"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/a",
                "https://example.com/b",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "recode_mp4",
            options: Options {
                container: Some(ContainerConversion::Recode("mp4".into())),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--recode-video",
                "mp4",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "remux_mp4",
            options: Options {
                container: Some(ContainerConversion::Remux("mp4".into())),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "mp4",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "remux_then_audio",
            options: Options {
                format: "bestaudio/best".into(),
                extract_audio: Some(AudioExtraction {
                    format: AudioFormat::Mp3,
                    quality: Some(5),
                }),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--merge-output-format",
                "mkv",
                "--extract-audio",
                "--audio-format",
                "mp3",
                "--audio-quality",
                "5",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "remux_webm_no_thumb",
            options: Options {
                container: Some(ContainerConversion::Remux("webm".into())),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--remux-video",
                "webm",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "sb_custom_cats",
            options: Options {
                sponsorblock: SponsorBlock::Mark {
                    categories: "sponsor,intro".into(),
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--sponsorblock-mark",
                "sponsor,intro",
                "--embed-chapters",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "sb_cut_default_kf",
            options: Options {
                sponsorblock: SponsorBlock::Remove {
                    categories: "default".into(),
                    force_keyframes: true,
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--sponsorblock-remove",
                "default",
                "--force-keyframes-at-cuts",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "sb_mark_basic_meta",
            options: Options {
                embed_metadata: true,
                sponsorblock: SponsorBlock::Mark {
                    categories: "sponsor".into(),
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--sponsorblock-mark",
                "sponsor",
                "--embed-metadata",
                "--embed-chapters",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "sb_mark_sponsor",
            options: Options {
                sponsorblock: SponsorBlock::Mark {
                    categories: "sponsor".into(),
                },
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--sponsorblock-mark",
                "sponsor",
                "--embed-chapters",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "subs_both_no_livechat",
            options: Options {
                subtitles: Some(Subtitles {
                    languages: "all,-live_chat".into(),
                    write_file: true,
                    embed: true,
                    auto_generated: false,
                }),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--embed-subs",
                "--write-subs",
                "--sub-langs",
                "all,-live_chat",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "subs_write_es",
            options: Options {
                subtitles: Some(Subtitles {
                    languages: "es".into(),
                    write_file: true,
                    embed: false,
                    auto_generated: false,
                }),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--write-subs",
                "--sub-langs",
                "es",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        // Empty languages mean every language but the live chat, and the
        // site's own generated subtitles can be asked for too.
        Scenario {
            name: "subs_default_langs_with_auto",
            options: Options {
                subtitles: Some(Subtitles {
                    languages: String::new(),
                    write_file: false,
                    embed: true,
                    auto_generated: true,
                }),
                verbose: false,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--embed-subs",
                "--write-auto-subs",
                "--sub-langs",
                "all,-live_chat",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        // MP4 chosen for merging: a single webm stream is rewrapped into
        // MP4 as well (for the thumbnail), not into MKV behind the user's
        // back. Checked on a real VP9 download by tests/e2e.rs.
        Scenario {
            name: "mp4_merge_rewraps_webm_to_mp4",
            options: Options {
                merge_output_format: Some("mp4".into()),
                verbose: false,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mp4",
                "--merge-output-format",
                "mp4",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        // Signed in through the browser's own cookies.
        Scenario {
            name: "cookies_from_browser",
            options: Options {
                cookies_from_browser: Some("firefox:work".into()),
                verbose: false,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "--cookies-from-browser",
                "firefox:work",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "template_channel",
            options: Options {
                output_template: "%(title)s - %(uploader)s [%(id)s].%(ext)s".into(),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s - %(uploader)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "template_custom",
            options: Options {
                output_template: "%(uploader)s/%(title)s.%(ext)s".into(),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "jpg",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(uploader)s/%(title)s.%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "thumb_none",
            options: Options {
                embed_thumbnail: false,
                convert_thumbnail: None,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "thumb_original",
            options: Options {
                convert_thumbnail: None,
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
        Scenario {
            name: "thumb_png",
            options: Options {
                convert_thumbnail: Some(ThumbnailFormat::Png),
                ..Options::default()
            },
            output_dir: None,
            urls: &["https://example.com/video"],
            argv: &[
                "--verbose",
                "--socket-timeout",
                "30",
                "--sleep-requests",
                "1.5",
                "--concurrent-fragments",
                "5",
                "--ffmpeg-location",
                "<SCRIPT_DIR>/bin/ffmpeg",
                "--js-runtimes",
                "deno:<SCRIPT_DIR>/bin/deno",
                "-f",
                "bestvideo*+bestaudio/best",
                "--embed-thumbnail",
                "--convert-thumbnails",
                "png",
                "--remux-video",
                "webm>mkv",
                "--merge-output-format",
                "mkv",
                "--restrict-filenames",
                "--output",
                "%(title)s [%(id)s].%(ext)s",
                "--",
                "https://example.com/video",
            ],
            exit: 0,
            fake_exit: 0,
        },
    ]
}

/// `EXE_SUFFIX` and the platform separator make a Windows-built path spell
/// `<SCRIPT_DIR>/bin\ffmpeg.exe` where every scenario above says
/// `<SCRIPT_DIR>/bin/ffmpeg`. Undo both so one set of scenarios covers every
/// platform. A no-op on Linux: `EXE_SUFFIX` is empty there and nothing else
/// in an argv contains a backslash.
fn normalize_tool_path(arg: &str) -> String {
    let stripped = arg
        .strip_suffix(std::env::consts::EXE_SUFFIX)
        .unwrap_or(arg);
    if cfg!(windows) {
        stripped.replace('\\', "/")
    } else {
        stripped.to_string()
    }
}

#[test]
fn every_scenario_produces_its_recorded_argv_and_exit() {
    let bin_dir = Path::new("<SCRIPT_DIR>/bin");
    let all = scenarios();
    let mut failures = Vec::new();

    for scenario in &all {
        let output_dir = scenario.output_dir.map(Path::new);
        let urls: Vec<String> = scenario.urls.iter().map(|u| u.to_string()).collect();
        let actual: Vec<String> = build_args(&scenario.options, bin_dir, output_dir, &urls)
            .into_iter()
            .map(|a| normalize_tool_path(&a.to_string_lossy()))
            .collect();
        let expected: Vec<String> = scenario.argv.iter().map(|s| s.to_string()).collect();
        if actual != expected {
            let first = actual
                .iter()
                .zip(&expected)
                .position(|(a, e)| a != e)
                .unwrap_or(actual.len().min(expected.len()));
            failures.push(format!(
                "{}: argv differs at position {first}\n  expected: {expected:?}\n  actual:   {actual:?}",
                scenario.name
            ));
        }

        let implied = match classify_exit(scenario.fake_exit) {
            Outcome::Completed | Outcome::StoppedAsConfigured => 0,
            Outcome::Failed(c) => c,
        };
        if implied != scenario.exit {
            failures.push(format!(
                "{}: yt-dlp exit {} should end as {}, engine says {implied}",
                scenario.name, scenario.fake_exit, scenario.exit
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} scenarios failed:\n{}",
        failures.len(),
        all.len(),
        failures.join("\n")
    );
}
